apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: intellidb
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres_admin_password"
  REPLICATION_PASSWORD: "replication_password"
  PATRONI_SUPERUSER_PASSWORD: "postgres_admin_password"
  PATRONI_REPLICATION_PASSWORD: "replication_password"